--Generated by TrackEdit, the Automation Track Editor
--Track: DownHill Track
Track = {
	Name = "DownHill Track",
	Start = { 15, 530 },
	Scale = 2,
	Layout = {0},
	LayoutInfo = {626.8},
	CornerRadius = {0},
	Slope = {-100},
	Sportiness = {0},
	Camber = {0},
	Split1 = 1,
	Split2 = 2
}
