--Generated by TrackEdit, the Automation Track Editor
--Track: Ehra Lessien
Track = {
	Name = "Ehra Lessien",
	Start = { 486, 326 },
	Scale = 0.129,
	Layout = {0, 1, 0, -1, 0, -1, 0, 1, 0},
	LayoutInfo = {3159.9, 22.7, 1222, 202.6, 8900, 202.8, 1067.5, 22.3, 850},
	CornerRadius = {0, 3000, 0, 380, 0, 375.2, 0, 3500, 0},
	Slope = {0, 0, 0, 0, 0, 0, 0, 0, 0},
	Sportiness = {0, 0, 0, 0, 0, 0, 0, 0, 0},
	Camber = {0, 15, 0, -30, 0, -30, 0, 15, 0},
	Split1 = 1,
	Split2 = 2
}
