--Generated by Automation Track Editor by Robert Maupin

--Track: Auto Club Speedway
Track = {
	Name = "Auto Club Speedway",
	Start = { 557, 560 },
	Scale = 0.718,
	Layout = {1, 1, 0, 1, 1},
	LayoutInfo = {22.5, 157.5, 729.8050139275759, 157.5, 22.5},
	CornerRadius = {1239.554317548746, 275.766016713092, 0, 275.766016713092, 1239.554317548746},
	Slope = {0, 0, 0, 0, 0},
	Sportiness = {1, 0, 0, 0, 0},
	Camber = {-11, -14, -3, -14, -11},
	Split1 = 1974.9303621169909,
	Split2 = 3218.9415041782727
}
