--Generated by TrackEdit, the Automation Track Editor
--Track: Dessau Rekordstrecke
Track = {
	Name = "Dessau Rekordstrecke",
	Start = { 83, 367 },
	Scale = 0.1125,
	Layout = {0, 0, 0},
	LayoutInfo = {1609.344, 3390.656, 5000},
	CornerRadius = {0, 0, 0},
	Slope = {0, 0, 0},
	Sportiness = {0, 0, 0},
	Camber = {0, 0, 0},
	Split1 = 1609.344,
	Split2 = 5000
}
